scrape_configs:
  - job_name: host_machine
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
  - job_name: bot
    static_configs:
      - targets: [ 'host.docker.internal:9101' ]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080